
version: '2'

services:

  orderer.code4fun.com:
    container_name: orderer.code4fun.com
    image: hyperledger/fabric-orderer:1.3.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/code4fun.com/orderers/orderer.code4fun.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/code4fun.com/orderers/orderer.code4fun.com/tls/:/var/hyperledger/orderer/tls
    - orderer.code4fun.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer1.geneva.code4fun.com:
    container_name: peer1.geneva.code4fun.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.geneva.code4fun.com
      - CORE_PEER_ADDRESS=peer1.geneva.code4fun.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.geneva.code4fun.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.geneva.code4fun.com:7051
      - CORE_PEER_LOCALMSPID=GenevaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/geneva.code4fun.com/peers/peer1.geneva.code4fun.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/geneva.code4fun.com/peers/peer2.geneva.code4fun.com/tls:/etc/hyperledger/fabric/tls
        - peer1.geneva.code4fun.com/:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer2.geneva.code4fun.com:
    container_name: peer2.geneva.code4fun.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.geneva.code4fun.com
      - CORE_PEER_ADDRESS=peer2.geneva.code4fun.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.geneva.code4fun.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.geneva.code4fun.com:7051
      - CORE_PEER_LOCALMSPID=GenevaMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/geneva.code4fun.com/peers/peer2.geneva.code4fun.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/geneva.code4fun.com/peers/peer2.geneva.code4fun.com/tls:/etc/hyperledger/fabric/tls
        - peer2.geneva.code4fun.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer1.zurich.code4fun.com:
    container_name: peer1.zurich.code4fun.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.zurich.code4fun.com
      - CORE_PEER_ADDRESS=peer1.zurich.code4fun.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.zurich.code4fun.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.zurich.code4fun.com:7051
      - CORE_PEER_LOCALMSPID=ZurichMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/zurich.code4fun.com/peers/peer1.zurich.code4fun.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/zurich.code4fun.com/peers/peer1.zurich.code4fun.com/tls:/etc/hyperledger/fabric/tls
        - peer1.zurich.code4fun.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer2.zurich.code4fun.com:
    container_name: peer2.zurich.code4fun.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.zurich.code4fun.com
      - CORE_PEER_ADDRESS=peer2.zurich.code4fun.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.zurich.code4fun.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.zurich.code4fun.com:7051
      - CORE_PEER_LOCALMSPID=ZurichMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/zurich.code4fun.com/peers/peer2.zurich.code4fun.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/zurich.code4fun.com/peers/peer2.zurich.code4fun.com/tls:/etc/hyperledger/fabric/tls
        - peer2.zurich.code4fun.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
